/** Semantic color roles from the "AI Design System" Figma library — bound to CSS custom properties in [[figma-export.tokens-bound.css]]. Prefer these over [[primitives]] in components. */
export const colors = {
  'bg/base': 'var(--bg-base)',
  'bg/layer-1': 'var(--bg-layer-1)',
  'bg/layer-2': 'var(--bg-layer-2)',
  'bg/layer-3': 'var(--bg-layer-3)',
  'bg/solid': 'var(--bg-solid)',
  'bg/state/hover': 'var(--bg-state-hover)',
  'bg/state/active': 'var(--bg-state-active)',
  'bg/state/disabled': 'var(--bg-state-disabled)',
  'bg/state/solid-active': 'var(--bg-state-solid-active)',
  'bg/state/container-hover': 'var(--bg-state-container-hover)',
  'bg/state/container-disabled': 'var(--bg-state-container-disabled)',
  'bg/mask': 'var(--bg-mask)',
  'bg/item': 'var(--bg-item)',
  'bg/item-on-layer': 'var(--bg-item-on-layer)',

  'text/primary': 'var(--text-primary)',
  'text/secondary': 'var(--text-secondary)',
  'text/tertiary': 'var(--text-tertiary)',
  'text/disabled': 'var(--text-disabled)',
  'text/placeholder': 'var(--text-placeholder)',
  'text/inverse': 'var(--text-inverse)',

  'border/primary': 'var(--border-primary)',
  'border/secondary': 'var(--border-secondary)',
  'border/tertiary': 'var(--border-tertiary)',
  'border/disabled': 'var(--border-disabled)',
  'border/placeholder': 'var(--border-placeholder)',
  'border/focus': 'var(--border-focus)',
  'border/inverse': 'var(--border-inverse)',

  'icon/primary': 'var(--icon-primary)',
  'icon/secondary': 'var(--icon-secondary)',
  'icon/tertiary': 'var(--icon-tertiary)',
  'icon/disabled': 'var(--icon-disabled)',
  'icon/placeholder': 'var(--icon-placeholder)',
  'icon/inverse': 'var(--icon-inverse)',
  'icon/item': 'var(--icon-item)',

  'primary/bg': 'var(--primary-bg)',
  'primary/bg-hover': 'var(--primary-bg-hover)',
  'primary/bg-active': 'var(--primary-bg-active)',
  'primary/bg-filled-hover': 'var(--primary-bg-filled-hover)',
  'primary/border': 'var(--primary-border)',
  'primary/border-hover': 'var(--primary-border-hover)',
  'primary/text': 'var(--primary-text)',
  'primary/text-hover': 'var(--primary-text-hover)',
  'primary/text-active': 'var(--primary-text-active)',
  'primary/solid': 'var(--primary-solid)',
  'primary/solid-hover': 'var(--primary-solid-hover)',
  'primary/solid-active': 'var(--primary-solid-active)',
  'primary/disabled': 'var(--primary-disabled)',
  'primary/disabled-on-layer': 'var(--primary-disabled-on-layer)',
  'primary/alias/primary-button': 'var(--primary-alias-primary-button)',

  'error/bg': 'var(--error-bg)',
  'error/bg-hover': 'var(--error-bg-hover)',
  'error/bg-active': 'var(--error-bg-active)',
  'error/bg-filled-hover': 'var(--error-bg-filled-hover)',
  'error/border': 'var(--error-border)',
  'error/border-hover': 'var(--error-border-hover)',
  'error/text': 'var(--error-text)',
  'error/text-hover': 'var(--error-text-hover)',
  'error/text-active': 'var(--error-text-active)',
  'error/solid': 'var(--error-solid)',
  'error/solid-hover': 'var(--error-solid-hover)',
  'error/solid-active': 'var(--error-solid-active)',
  'error/disabled': 'var(--error-disabled)',

  'warning/bg': 'var(--warning-bg)',
  'warning/bg-hover': 'var(--warning-bg-hover)',
  'warning/bg-active': 'var(--warning-bg-active)',
  'warning/border': 'var(--warning-border)',
  'warning/text': 'var(--warning-text)',
  'warning/solid': 'var(--warning-solid)',
  'warning/disabled': 'var(--warning-disabled)',

  'success/bg': 'var(--success-bg)',
  'success/bg-hover': 'var(--success-bg-hover)',
  'success/border': 'var(--success-border)',
  'success/text': 'var(--success-text)',
  'success/solid': 'var(--success-solid)',
  'success/disabled': 'var(--success-disabled)',

  'info/bg': 'var(--info-bg)',
  'info/border': 'var(--info-border)',
  'info/text': 'var(--info-text)',
  'info/solid': 'var(--info-solid)',
  'info/disabled': 'var(--info-disabled)',

  'link/default': 'var(--link-link-default)',
  'link/hover': 'var(--link-link-hover)',
  'link/active': 'var(--link-link-active)',
  'link/visited': 'var(--link-visited)',
  'link/danger-default': 'var(--link-danger-default)',
  'link/danger-hover': 'var(--link-danger-hover)',
  'link/danger-active': 'var(--link-danger-active)',
  'link/danger-visited': 'var(--link-danger-visited)',
} as const;

export type ColorToken = keyof typeof colors;
